---
- name: dependencies
  package: name={{ item }} state=present
  with_items:
    - ruby-dev
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libxml2-dev
- name: install vagrant
  apt: name=vagrant state=present install_recommends=no
- name: vagrant-aws plugin
  command: vagrant plugin install vagrant-aws warn=no
  become_user: "{{ vagrant_plugin_user }}"
- name: vagrant aws dummy box
  command: vagrant box add dummy {{ vagrant_aws_box_url }}
  become_user: "{{ vagrant_plugin_user }}"
