apiVersion: apps/v1beta1
kind: Deployment
namespace: default
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: alanhohn/todo:{{ tag }}
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "{{ todo_database_url }}"
        ports:
        - containerPort: 5000
