apiVersion: apps/v1beta1
kind: Deployment
namespace: default
metadata:
  name: tododb
  labels:
    app: tododb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tododb
  template:
    metadata:
      labels:
        app: tododb
    spec:
      containers:
      - name: tododb
        image: postgres:10.4
        env:
        - name: POSTGRES_USER
          value: "{{ postgresql_user }}"
        - name: POSTGRES_PASSWORD
          value: "{{ postgresql_password }}"
        - name: PGDATA
          value: "/data/pgdata"
        volumeMounts:
        - mountPath: /data
          name: todo-data
      volumes:
        - name: todo-data
          persistentVolumeClaim:
           claimName: todo-data
